FROM i386/alpine:3.16

RUN apk add build-base libx11-dev libxext-dev linux-headers -t build
#RUN apk add libx11 libxext

RUN addgroup -S inferno
RUN adduser --disabled-password --ingroup inferno inferno
USER inferno

ENV INFERNO=/usr/acme-sac
ENV objtype=386

WORKDIR $INFERNO
COPY --chown=inferno . $INFERNO

# setup a custom mkconfig
RUN echo > mkconfig ROOT=$INFERNO  \
    && echo >>mkconfig TKSTYLE=std \
    && echo >>mkconfig SYSHOST=Linux  \
    && echo >>mkconfig SYSTARG=Linux  \
    && echo >>mkconfig OBJTYPE=${objtype}    \
    && echo >>mkconfig 'OBJDIR=$SYSTARG/$OBJTYPE'  \
    && echo >>mkconfig '<$ROOT/mkfiles/mkhost-$SYSHOST' \
    && echo >>mkconfig '<$ROOT/mkfiles/mkfile-$SYSTARG-$OBJTYPE' 

ENV PATH="$INFERNO/Linux/${objtype}/bin:${PATH}"
RUN ./makemk.sh \
	&& mk clean \
	&& mk install \
	&& mk clean

EXPOSE 8080
ENTRYPOINT ["emu"]
CMD ["-r", "/usr/acme-sac"]
